### ISSUE TITLE
The link-repos script fails to link repositories even if started with administrative privileges

### ISSUE THREAD

**Issue by AlisherAmonulloev** [DevExpress/devextreme-demos#41]
this command fails
npm run link-repos

this is the error:

```stacktrace
found 15 vulnerabilities (9 low, 4 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm ERR! code EEXIST
npm ERR! path C:\Users\johnn\AppData\Roaming\npm\node_modules\devextreme\bin\bundler-init.js
npm ERR! dest C:\Users\johnn\AppData\Roaming\npm\devextreme-bundler-init
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\johnn\AppData\Roaming\npm\node_modules\devextreme\bin\bundler-init.js' -> 'C:\Users\johnn\AppData\Roaming\npm\devextreme-bundler-init'
npm ERR! File exists: C:\Users\johnn\AppData\Roaming\npm\devextreme-bundler-init
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johnn\AppData\Roaming\npm-cache\_logs\2020-08-11T08_48_40_412Z-debug.log
Error: Command failed: cd F:\repositories\DxDemos\JSDemos\node_modules && npm link F:\repositories\DevExtreme\artifacts\npm\devextreme
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at systemSync (F:\repositories\DxDemos\utils\cp_utils.js:5:23)
    at Object.processRepository (F:\repositories\DxDemos\utils\repos_helper.js:23:9)
    at F:\repositories\DxDemos\utils\link-repos.js:19:21
    at Array.forEach (<anonymous>)
    at mainRoutine (F:\repositories\DxDemos\utils\link-repos.js:14:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async F:\repositories\DxDemos\utils\link-repos.js:25:14 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 38580,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devextreme-demos@20.2.0 prepare-js:dev: `cd JSDemos && npm i && node ../utils/create-config.js && node ../utils/link-repos.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devextreme-demos@20.2.0 prepare-js:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johnn\AppData\Roaming\npm-cache\_logs\2020-08-11T08_48_40_472Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devextreme-demos@20.2.0 prepare-all: `npm run prepare-js:dev && npm run prepare-mvc && npm run prepare-netcore`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devextreme-demos@20.2.0 prepare-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johnn\AppData\Roaming\npm-cache\_logs\2020-08-11T08_48_40_491Z-debug.log

```

**Comment by AlisherAmonulloev** [comment]
closed since it occurs rarely.
